# Generated by Django 2.2.2 on 2019-06-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('is_manager', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('medical_checkup_location', models.TextField()),
            ],
            options={
                'db_table': 'work_locations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '男性'), (1, '女性'), (2, 'その他')])),
                ('birthday', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Position')),
                ('work_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.WorkLocation')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
