# Generated by Django 2.2.2 on 2019-06-13 06:44

from django.db import migrations, models
import employee.types


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(employee.types.Gender(0), '男性'), (employee.types.Gender(1), '女性')]),
        ),
    ]
