# Generated by Django 2.2.2 on 2019-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_checkup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcheckup',
            name='judgement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
