# Generated by Django 2.2.2 on 2019-06-11 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_checkup', '0002_auto_20190610_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcheckup',
            name='judgement_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='medicalcheckup',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='medicalcheckup',
            index=models.Index(fields=['employee', 'target_year', 'conducted_year', 'conducted_month'], name='medical_che_employe_8358e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalcheckup',
            constraint=models.UniqueConstraint(fields=('employee', 'target_year', 'conducted_year', 'conducted_month'), name='unique_medical_checkup_employee'),
        ),
    ]
