# Generated by Django 2.2.2 on 2019-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_checkup', '0003_auto_20190611_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcheckup',
            name='judgement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
